// This is a fun game program of guessing the number
// User can run the program and ask for a number
// He has to guess the number in minimum number of attempts
// Also the Random Number will be generated by the program

package org;

import java.util.Random;
import java.util.Scanner;

class GuessTheNumber{
	private int actual;
	private int guessed;
	private int noOfGuesses;
	
	public GuessTheNumber(){
		Random r = new Random();
		actual = r.nextInt(100);
		// or ThreadLocalRandom.current().nextInt(Min, Max + 1); //Min=1 max = 100
	}
	
	public void setnoOfGuesses(int n) {
		this.noOfGuesses = n;
	}
	
	public int getnoOfGuesses() {
		return this.noOfGuesses;
	}
	
	public int UserInput(){
		System.out.println("Enter a Number between 0-100: ");
		Scanner sc = new Scanner(System.in);
		guessed = sc.nextInt();
		return guessed;
	}
	
	public boolean isCorrect(int inp) {
		this.guessed = inp;
		if(guessed>actual) {
			System.out.println("The number is too High");
			return false;
		}
		else if(guessed<actual) {
			System.out.println("The number is too Low");
			return false;
		}
		else {
			System.out.println("Hurray! You Entered the correct number.");
			return true;
		}
	}
}

public class D2_P1_GuessTheNumber {
	
	public static void main(String[] args) {
		int inp;
		GuessTheNumber gtn = new GuessTheNumber();
		gtn.setnoOfGuesses(0);
		boolean check = false;
		while(!check) {
			inp = gtn.UserInput();
			check = gtn.isCorrect(inp);
			gtn.setnoOfGuesses( 1 + gtn.getnoOfGuesses());
		}
		
		System.out.println("You guessed it in "+gtn.getnoOfGuesses()+" guesses.");
		
		
	}
	
}
