numbers = [2, 3,2,1,34,]
numbers.insert(2,5)
numbers.append(10)
numbers.remove(5)
#numbers.clear()
numbers.pop()
print(numbers)
print(numbers.index(34))
print(50 in numbers)
print(numbers.count(1))
numbers.sort()
numbers.reverse()
number2 = numbers.copy()
print(numbers)
print(number2)